services:
  grande-gpu:
    build: .
    runtime: nvidia
    volumes:
      - ./results:/app/results
      - ./data:/app/data
      - ./experiments_paper:/app/experiments_paper
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root 